import { Question } from './types';

export const questions: Question[] = [
  // --- DOMAIN 1.0: NETWORKING CONCEPTS (23%) ---
  {
    id: 'scen1',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.8 Modern Envs',
    question: 'A network administrator is designing a highly scalable data center fabric. They need to provide Layer 2 connectivity over a Layer 3 spine-leaf architecture while allowing for over 16 million segments. Which technology is BEST suited for this requirement?',
    options: ['VXLAN', 'STP', 'VLAN', '802.1Q'],
    correctAnswer: 'VXLAN',
    explanation: {
      whyCorrect: "VXLAN (Virtual Extensible LAN) is the industry standard for large data centers. It uses a 24-bit VNI (VXLAN Network Identifier), which supports over 16 million unique segments, far exceeding the 4,096-segment limit of traditional 802.1Q VLANs.",
      whyWrong: [
        { option: "STP", reason: "STP (Spanning Tree Protocol) is for loop prevention in Layer 2 networks, not for creating massive virtual segments." },
        { option: "VLAN", reason: "VLANs are limited to 4,096 IDs, which is insufficient for the high scalability required in modern multi-tenant cloud data centers." },
        { option: "802.1Q", reason: "This is the standard trunking protocol for VLANs, but it doesn't provide the level of scalability that VXLAN encapsulates." }
      ]
    },
    weight: 10,
  },
  {
    id: 'scen2',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.8 Modern Envs',
    question: 'An organization needs to optimize cloud application performance for branch offices by dynamically routing traffic based on real-time link quality and application requirements. Which solution should be implemented?',
    options: ['SD-WAN', 'BGP', 'Site-to-Site VPN', 'Static Routing'],
    correctAnswer: 'SD-WAN',
    explanation: {
      whyCorrect: "SD-WAN (Software-Defined Wide Area Network) provides dynamic path selection (DPS), allowing traffic to be routed over MPLS, Broadband, or LTE based on performance metrics like jitter and latency.",
      whyWrong: [
        { option: "BGP", reason: "BGP is for path exchange between Autonomous Systems; it doesn't natively handle application-aware dynamic routing based on link health." },
        { option: "Site-to-Site VPN", reason: "Site-to-Site VPN provides a fixed secure tunnel but typically lacks the real-time link quality monitoring and dynamic steering of SD-WAN." },
        { option: "Static Routing", reason: "Static routing is manual and does not adapt automatically to failures or changes in link performance." }
      ]
    },
    weight: 10,
  },
  {
    id: 'multi1',
    type: 'multi-select',
    domain: '1.0 Concepts',
    objective: '1.4 Ports & Protocols',
    question: 'A security engineer is configuring a stateful firewall. Which of the following ports should be allowed to facilitate secure remote administration and secure file transfer? (Select TWO).',
    options: ['22', '23', '443', '445', '990', '21'],
    correctAnswer: ['22', '990'],
    explanation: {
      whyCorrect: "Port 22 is natively used by SSH (secure remote administration) and SFTP. Port 990 is used for FTPS (FTP over TLS/SSL) implicit mode, ensuring encrypted file transfers.",
      whyWrong: [
        { option: "23", reason: "Port 23 is Telnet, which transfers data and credentials in plaintext, making it highly insecure." },
        { option: "443", reason: "Port 443 is HTTPS; while secure, it is for web traffic rather than direct remote administration or standard file transfer protocols." },
        { option: "445", reason: "Port 445 is SMB; it is commonly used for file sharing in local networks but is not a standard secure remote admin protocol for these scenarios." },
        { option: "21", reason: "Port 21 is standard FTP; like Telnet, it is plaintext and insecure for modern corporate administration." }
      ]
    },
    weight: 10,
  },

  // --- DOMAIN 2.0: NETWORK IMPLEMENTATION (20%) ---
  {
    id: 'scen3',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.1 Routing Technologies',
    question: 'You are configuring a router for a large enterprise. You need to use an interior gateway protocol that provides fast convergence and supports large-scale hierarchies using areas. Which protocol is the BEST choice?',
    options: ['OSPF', 'BGP', 'RIPv2', 'EGP'],
    correctAnswer: 'OSPF',
    explanation: 'OSPF is a link-state IGP that uses SPF for fast convergence and supports hierarchical design through areas.',
    weight: 10,
  },
  {
    id: 'scen4',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.1 Routing Technologies',
    question: 'A network technician is troubleshooting a routing issue between two different Autonomous Systems. Which protocol is responsible for exchanging routing information between them?',
    options: ['BGP', 'OSPF', 'EIGRP', 'IS-IS'],
    correctAnswer: 'BGP',
    explanation: 'Border Gateway Protocol (BGP) is the standard Exterior Gateway Protocol (EGP) used to route between Autonomous Systems.',
    weight: 10,
  },

  // --- DOMAIN 3.0: NETWORK OPERATIONS (19%) ---
  {
    id: 'ac1',
    type: 'acronym',
    domain: '3.0 Operations',
    objective: '3.3 Disaster Recovery',
    question: 'Acronym: A service level agreement specifies that a critical server must be back online within 4 hours of a failure. Which metric does this represent?',
    options: ['RTO', 'RPO', 'MTBF', 'MTTR'],
    correctAnswer: 'RTO',
    explanation: 'Recovery Time Objective (RTO) defines the maximum acceptable duration of downtime.',
    weight: 10,
  },
  {
    id: 'ac2',
    type: 'acronym',
    domain: '3.0 Operations',
    objective: '3.3 Disaster Recovery',
    question: 'Acronym: Your organization performs daily backups at midnight. A catastrophic failure occurs at 10 PM. The organization realizes they have lost 22 hours of data. Which metric measures this tolerable data loss?',
    options: ['RPO', 'RTO', 'MTTF', 'MTD'],
    correctAnswer: 'RPO',
    explanation: 'Recovery Point Objective (RPO) defines the maximum age of data that can be lost from a backup.',
    weight: 10,
  },

  // --- DOMAIN 4.0: NETWORK SECURITY (14%) ---
  {
    id: 'scen5',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.1 Security Concepts',
    question: 'A CISO wants to implement a security model where no user or device is trusted by default, even if they are inside the corporate network. Which architecture should be adopted?',
    options: ['Zero Trust', 'Defense in Depth', 'De-Militarized Zone', 'Air Gapping'],
    correctAnswer: 'Zero Trust',
    explanation: 'Zero Trust architecture requires continuous verification of all subjects (users, devices, apps) regardless of their location.',
    weight: 10,
  },
  {
    id: 'scen6',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'A technician wants to prevent unauthorized laptops from connecting to a desktop Ethernet port in a lobby. Which of the following would be the MOST effective solution?',
    options: ['Port Security', 'DHCP Snooping', 'VLAN Pooling', 'IP Source Guard'],
    correctAnswer: 'Port Security',
    explanation: 'Port security allows you to restrict the MAC addresses that can connect to a physical switch port.',
    weight: 10,
  },

  // --- DOMAIN 5.0: NETWORK TROUBLESHOOTING (24%) ---
  {
    id: 'ts1',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'Users report they cannot access a shared drive. You have questioned the users and identified that only one floor is affected. You have just established a theory of probable cause. What is the NEXT step you should take?',
    options: ['Test the theory', 'Establish a plan of action', 'Verify full system functionality', 'Document findings'],
    correctAnswer: 'Test the theory',
    explanation: 'After establishing a theory of probable cause, the next step in the CompTIA methodology is to test the theory to confirm the cause.',
    weight: 10,
  },
  {
    id: 'ts2',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'You have implemented a missing routing entry on a core router and verified that users can now reach the internet. What is the FINAL step in the troubleshooting methodology?',
    options: ['Document findings', 'Perform a root cause analysis', 'Verify functionality', 'Create a new baseline'],
    correctAnswer: 'Document findings',
    explanation: 'The final step is to document findings, actions, and outcomes to provide a reference for future issues.',
    weight: 10,
  },
  {
    id: 'ts3',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'A network technician is called to fixed a connectivity issue. After identifying the problem and establishing a theory of probable cause, the technician tests the theory and confirms it is correct. Which of the following is the BEST next step?',
    options: ['Establish a plan of action to resolve the problem', 'Implement the solution immediately', 'Verify full system functionality', 'Document the verified theory'],
    correctAnswer: 'Establish a plan of action to resolve the problem',
    explanation: 'Once a theory is tested and confirmed, the next step is to establish a plan of action to resolve the problem and identify potential effects.',
    weight: 10,
  },
  {
    id: 'ts4',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'Numerous users in a branch office report they cannot access any external websites. You observe that all local resources are reachable. Which of the following should you perform FIRST?',
    options: ['Question the users to identify any changes', 'Examine the core router interface logs', 'Restart the edge gateway', 'Replace the upstream fiber patch cable'],
    correctAnswer: 'Question the users to identify any changes',
    explanation: 'The very first step in the troubleshooting methodology is to identify the problem, which starts with questioning the users and identifying symptoms/changes.',
    weight: 10,
  },
  {
    id: 'ts5',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'A technician has replaced a faulty SFP+ module on a switch and confirmed that the link light is active. What is the MOST important next step according to the CompTIA troubleshooting model?',
    options: ['Verify full system functionality', 'Implement preventive measures', 'Document the change', 'Establish a new theory'],
    correctAnswer: 'Verify full system functionality',
    explanation: 'After implementing a solution, you must verify full system functionality and, if applicable, implement preventive measures.',
    weight: 10,
  },
  {
    id: 'cli1',
    type: 'cli',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'Which command would you use to view the mapping between Layer 2 MAC addresses and Layer 3 IP addresses on a local Windows machine?',
    options: ['arp -a', 'nslookup', 'netstat -r', 'ipconfig /all'],
    correctAnswer: 'arp -a',
    explanation: 'The arp command displays the Address Resolution Protocol (ARP) table, which maps IP addresses to MAC addresses.',
    weight: 10,
  },
  {
    id: 'cli2',
    type: 'cli',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'Traffic is heavily congested on a specific VLAN. A technician wants to see the source and destination of all packets leaving a specific interface. Which tool is BEST suited for this task?',
    options: ['tcpdump', 'traceroute', 'ping', 'dig'],
    correctAnswer: 'tcpdump',
    explanation: 'tcpdump is a packet analyzer that allows for real-time capture and inspection of network traffic.',
    weight: 10,
  },
  {
    id: 'cli3',
    type: 'cli',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A user cannot reach a website by its name but can ping its IP address. Which command-line tool would be BEST to diagnose the issue?',
    options: ['nslookup', 'netstat', 'nbtstat', 'route'],
    correctAnswer: 'nslookup',
    explanation: 'nslookup is used to query DNS, which is responsible for resolving names to IP addresses.',
    weight: 10,
  },
  {
    id: 'multi2',
    type: 'multi-select',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A network engineer needs to verify the path that packets take to a remote server and check for open ports on that server. Which of the following tools should be used? (Select TWO).',
    options: ['tracert', 'nmap', 'nslookup', 'ipconfig', 'arp', 'netstat'],
    correctAnswer: ['tracert', 'nmap'],
    explanation: 'tracert (or traceroute) shows the path, and nmap is a powerful port scanner.',
    weight: 10,
  },
  // --- VISUAL PBQs ---
  {
    id: 'vis1',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'A network technician is repairing a high-density fiber patch panel. Which connector type is shown in the image, characterized by its "Local Connector" small form factor and push-pull latching mechanism?',
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800',
    options: ['LC', 'SC', 'ST', 'MTRJ'],
    correctAnswer: 'LC',
    explanation: 'The LC (Local Connector) is a small form factor connector that uses a 1.25mm ferrule and a tab-style locking mechanism, common in SFP modules.',
    weight: 10,
  },
  {
    id: 'vis2',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.6 Topology',
    question: 'Observe the data center layout in the image. Which topology is depicted, utilizing a non-blocking architecture that allows any leaf switch to talk to any other leaf switch via a single hop through the spine?',
    imageUrl: 'https://images.unsplash.com/photo-1551703599-6b3e8379aa8c?auto=format&fit=crop&q=80&w=800',
    options: ['Spine-and-Leaf', 'Three-tier Hierarchical', 'Mesh', 'Ring'],
    correctAnswer: 'Spine-and-Leaf',
    explanation: 'Spine-and-Leaf is a two-tier architecture where every leaf switch connects to every spine switch, providing high bandwidth and low latency.',
    weight: 10,
  },
  {
    id: 'vis3',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'A technician is interconnecting two switches in the same rack. Which specialized cable is shown, combining a Twinaxial copper cable with integrated SFP+ transceivers?',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc4b?auto=format&fit=crop&q=80&w=800',
    options: ['Twinaxial DAC', 'AOC (Active Optical)', 'Cat8 Ethernet', 'Single-Mode Fiber'],
    correctAnswer: 'Twinaxial DAC',
    explanation: 'Direct Attach Copper (DAC) cables are Twinaxial cables with factory-attached SFP+ connectors, used for short-range Top-of-Rack connections.',
    weight: 10,
  },
  {
    id: 'vis4',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'Which legacy connector type is shown, ubiquitous in older 10Base2 Ethernet networks and still used for modern CCTV coaxial connections?',
    imageUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&q=80&w=800',
    options: ['BNC', 'F-Type', 'RJ-45', 'DB-9'],
    correctAnswer: 'BNC',
    explanation: 'BNC (Bayonet Neill-Concelman) connectors are RF connectors used with coaxial cables, featuring a bayonet mount locking mechanism.',
    weight: 10,
  },
  {
    id: 'vis5',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'Identify the fiber connector shown, often called the "Subscriber Connector" or "Standard Connector," known for its square shape and push-pull mechanism.',
    imageUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?auto=format&fit=crop&q=80&w=800',
    options: ['SC', 'LC', 'ST', 'FC'],
    correctAnswer: 'SC',
    explanation: 'The SC (Subscriber Connector) uses a 2.5mm ferrule and has a push-pull latching mechanism. It is larger than the LC connector.',
    weight: 10,
  },

  // --- DEEP SYLLABUS EXPANSION ---
  {
    id: 'deep1',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Storage',
    question: 'A financial firm requires a storage solution that allows servers to access raw block-level storage over a dedicated high-speed network. Which technology should be implemented?',
    options: ['SAN (Storage Area Network)', 'NAS (Network Attached Storage)', 'Cloud Storage', 'DFS'],
    correctAnswer: 'SAN (Storage Area Network)',
    explanation: 'SAN provides block-level access to storage, appearing as local disks to the server, typically using Fibre Channel or iSCSI.',
    weight: 10,
  },
  {
    id: 'deep2',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Storage',
    question: 'An office needs a centralized file server that connects to the existing Ethernet network and provides file-level access via SMB/NFS. Which device is BEST?',
    options: ['NAS', 'SAN', 'vSAN', 'Tape Drive'],
    correctAnswer: 'NAS',
    explanation: 'NAS (Network Attached Storage) provides file-level storage services to other devices on the network, typically over standard Ethernet.',
    weight: 10,
  },
  {
    id: 'deep3',
    type: 'multi-select',
    domain: '1.0 Concepts',
    objective: '1.4 Ports & Protocols',
    question: 'A systems administrator is hardening a directory services environment. Which ports should be allowed to support encrypted directory lookups and VoIP session initiation? (Select TWO).',
    options: ['636', '5061', '389', '5060', '1433', '1521'],
    correctAnswer: ['636', '5061'],
    explanation: 'Port 636 is LDAPS (LDAP over SSL/TLS). Port 5061 is SIP over TLS (secure).',
    weight: 10,
  },
  {
    id: 'deep4',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.4 DNS Records',
    question: 'You are adding an IPv6 record for a new web server in the corporate DNS zone. Which record type should you create?',
    options: ['AAAA', 'A', 'CNAME', 'PTR', 'MX', 'NS'],
    correctAnswer: 'AAAA',
    explanation: 'AAAA records map a hostname to an IPv6 address. (A records map to IPv4).',
    weight: 10,
  },
  {
    id: 'deep5',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.4 DNS Records',
    question: 'A technician needs to create a DNS alias so that "shop.example.com" points to "server1.example.com". Which record type is required?',
    options: ['CNAME', 'A', 'MX', 'TXT'],
    correctAnswer: 'CNAME',
    explanation: 'CNAME (Canonical Name) records are used to create aliases for existing A records.',
    weight: 10,
  },
  {
    id: 'deep6',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.4 DNS Records',
    question: 'An administrator needs to perform a reverse lookup to find the hostname associated with a specific IP address. Which DNS record is queried?',
    options: ['PTR', 'A', 'NS', 'SOA'],
    correctAnswer: 'PTR',
    explanation: 'PTR (Pointer) records facilitate reverse DNS lookups, mapping an IP address to a hostname.',
    weight: 10,
  },
  {
    id: 'deep7',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'An organization needs a solution that can automatically block malicious traffic in real-time as it traverses the network perimeter. Which device is MOST suitable?',
    options: ['IPS', 'IDS', 'Syslog Server', 'Load Balancer'],
    correctAnswer: 'IPS',
    explanation: 'An Intrusion Prevention System (IPS) is placed inline and can actively block or drop malicious traffic, whereas an IDS is out-of-band and only alerts.',
    weight: 10,
  },
  {
    id: 'deep8',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A switch interface is reporting a high number of CRC errors. Which of the following is the MOST likely cause?',
    options: ['Faulty cable or interference', 'Duplex mismatch', 'VLAN tagging error', 'Routing loop'],
    correctAnswer: 'Faulty cable or interference',
    explanation: 'Cyclic Redundancy Check (CRC) errors indicate packets were corrupted in transit, usually due to bad cables, connectors, or EMI.',
    weight: 10,
  },
  {
    id: 'deep9',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A user reports extremely slow network performance. The technician notices that the switch port is set to Full-Duplex while the workstation is set to Half-Duplex. What is this issue called?',
    options: ['Duplex Mismatch', 'Speed Incompatibility', 'Auto-negotiation loop', 'Switching Loop'],
    correctAnswer: 'Duplex Mismatch',
    explanation: 'A duplex mismatch occurs when two connected devices use different duplex settings, causing collisions and significant performance degradation.',
    weight: 10,
  },
  {
    id: 'deep10',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A network monitor shows an interface is receiving "giants." What does this typically mean?',
    options: ['Packets exceed the MTU size', 'Packets are too small', 'Packets have invalid headers', 'The buffer is overflowing'],
    correctAnswer: 'Packets exceed the MTU size',
    explanation: 'Giants are packets that exceed the maximum transmission unit (MTU) size (usually 1518 bytes for standard Ethernet).',
    weight: 10,
  },
  {
    id: 'deep11',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'An interface is reporting "runts." Which of the following is the BEST definition of a runt?',
    options: ['Packets smaller than 64 bytes', 'Packets larger than 1518 bytes', 'Packets with incorrect checksums', 'Packets that timed out'],
    correctAnswer: 'Packets smaller than 64 bytes',
    explanation: 'Runts are packets that are smaller than the minimum Ethernet frame size of 64 bytes, often caused by collisions.',
    weight: 10,
  },
  {
    id: 'deep12',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.4 Protocols',
    question: 'A technician is configuring a VoIP system. Which protocol is primarily responsible for establishing, maintaining, and terminating the call session?',
    options: ['SIP', 'RTP', 'RTCP', 'H.323'],
    correctAnswer: 'SIP',
    explanation: 'Session Initiation Protocol (SIP) handles the signaling for VoIP calls, while RTP carries the actual voice data.',
    weight: 10,
  },
  {
    id: 'deep13',
    type: 'multi-select',
    domain: '3.0 Operations',
    objective: '3.4 DNS Servers',
    question: 'Which of the following DNS server types is responsible for providing the final, definitive IP address mapping for a requested domain? (Select TWO).',
    options: ['Authoritative Name Server', 'Primary DNS Server', 'Recursive Resolver', 'Caching Server', 'Forwarder', 'Stub Resolver'],
    correctAnswer: ['Authoritative Name Server', 'Primary DNS Server'],
    explanation: 'Authoritative servers (which can be primary or secondary) hold the actual DNS records for a domain.',
    weight: 10,
  },
  {
    id: 'deep14',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'A security auditor recommends moving the IDS to a "passive" or "out-of-band" configuration. How will the IDS receive traffic in this setup?',
    options: ['Port Mirroring/TAP', 'Inline bridging', 'Proxy Server', 'SSL Decryption'],
    correctAnswer: 'Port Mirroring/TAP',
    explanation: 'Passive IDS receives a copy of traffic via a SPAN port (Port Mirroring) or a network TAP, ensuring it does not impact network latency.',
    weight: 10,
  },
  {
    id: 'deep15',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Storage',
    question: 'Which storage protocol is designed specifically to run over high-speed Fibre Channel networks, providing low-latency, lossless block-level access?',
    options: ['FCP (Fibre Channel Protocol)', 'iSCSI', 'FCoE', 'SMB'],
    correctAnswer: 'FCP (Fibre Channel Protocol)',
    explanation: 'FCP is the standard protocol for transporting SCSI commands over Fibre Channel networks.',
    weight: 10,
  },
  // --- SUBNET TIME-ATTACK QUESTIONS ---
  {
    id: 'sub1',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'You are provided with the network 192.168.10.0/24. You need to create 4 equal-sized subnets. What will be the new subnet mask for these networks?',
    options: ['/25', '/26', '/27', '/28'],
    correctAnswer: '/26',
    explanation: 'To create 4 subnets (2^2), you need to borrow 2 bits from the host portion. /24 + 2 = /26.',
    weight: 10,
  },
  {
    id: 'sub2',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'Given the IP address 172.16.50.0/27, what is the maximum number of usable host addresses available in this subnet?',
    options: ['30', '32', '62', '14'],
    correctAnswer: '30',
    explanation: 'A /27 has 5 host bits remaining (32-27=5). 2^5 = 32 total addresses. Subtract 2 for network and broadcast: 32 - 2 = 30 usable hosts.',
    weight: 10,
  },
  {
    id: 'sub3',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'What is the CIDR equivalent for the subnet mask 255.255.255.224?',
    options: ['/27', '/28', '/26', '/25'],
    correctAnswer: '/27',
    explanation: '224 in binary is 11100000. This adds 3 bits to the default /24, making it 27 bits total.',
    weight: 10,
  },
  {
    id: 'sub4',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'An organization needs a subnet for 500 users. Which of the following is the MOST efficient subnet mask for this requirement?',
    options: ['/23', '/22', '/24', '/21'],
    correctAnswer: '/23',
    explanation: 'A /23 provides 2^9 = 512 total addresses (510 usable), which is the smallest mask that accommodates 500 users.',
    weight: 10,
  },
  {
    id: 'sub5',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'Which of the following is the correct wildcard mask for a /28 subnet?',
    options: ['0.0.0.15', '0.0.0.31', '0.0.0.7', '0.0.0.63'],
    correctAnswer: '0.0.0.15',
    explanation: 'A /28 mask is 255.255.255.240. The wildcard mask is the inverse: 0.0.0.(255-240) = 0.0.0.15.',
    weight: 10,
  },
  // --- MODERN SYLLABUS UPGRADES (IaC, ZTA, IPv6, HA) ---
  {
    id: 'iac1',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.1 IaC',
    question: 'A DevOps engineer notices that several servers have slightly different configurations despite being deployed from the same initial script. This deviation from the intended state is known as:',
    options: ['Configuration Drift', 'Dynamic Inventory', 'Mutable Infrastructure', 'Orchestration Lag'],
    correctAnswer: 'Configuration Drift',
    explanation: 'Configuration drift occurs when undocumented changes are made to systems over time, causing them to deviate from their baseline configuration.',
    weight: 10,
  },
  {
    id: 'ipv6_1',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'An organization is migrating to IPv6 but needs to allow its IPv6-only servers to communicate with legacy IPv4-only services on the internet. Which transition mechanism is BEST suited for this?',
    options: ['NAT64', 'Dual Stack', '6to4 Tunneling', 'ISATAP'],
    correctAnswer: 'NAT64',
    explanation: 'NAT64 allows IPv6-only clients to communicate with IPv4-only servers by translating the headers at a gateway.',
    weight: 10,
  },
  {
    id: 'zta_1',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.1 Security Concepts',
    question: 'In a Zero Trust Architecture, which principle ensures that users and applications are granted only the minimum level of access necessary to perform their functions?',
    options: ['Least Privilege', 'Implicit Trust', 'Defense in Depth', 'Micro-segmentation'],
    correctAnswer: 'Least Privilege',
    explanation: 'Least Privilege is the cornerstone of ZTA, ensuring that subjects only have access to resources required for their specific role.',
    weight: 10,
  },
  {
    id: 'ha1',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.2 High Availability',
    question: 'A network design requires two load balancers where both units simultaneously handle incoming traffic to maximize throughput. Which HA configuration is being used?',
    options: ['Active-Active', 'Active-Passive', 'N+1 Redundancy', 'Hot Standby'],
    correctAnswer: 'Active-Active',
    explanation: 'In an Active-Active configuration, all nodes simultaneously handle and share the traffic load. The key distinction is that Active-Active provides both load balancing and redundancy, whereas Active-Passive relies on a standby unit.',
    weight: 10,
  },
  {
    id: 'ha2',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.2 High Availability',
    question: 'A critical firewall cluster is configured so that one unit processes all traffic while the second unit monitors the first and only takes over if the primary unit fails. What is this configuration called?',
    options: ['Active-Passive', 'Active-Active', 'Load Balancing', 'Round Robin'],
    correctAnswer: 'Active-Passive',
    explanation: 'In an Active-Passive (Failover) configuration, one unit is active while the other remains in a standby/idle state. The standby unit only processes traffic if the active unit fails. It does NOT share the load.',
    weight: 10,
  },
  {
    id: 'cli_i1',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A technician suspect a DNS issue. Type the full command to interactively query the default DNS server for information about "google.com".',
    options: [], // Not used for interactive
    correctAnswer: 'nslookup google.com',
    explanation: 'The nslookup command is used to query DNS servers. Typing the domain name as an argument returns its A/AAAA records.',
    weight: 10,
  },
  {
    id: 'cli_i2',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'You need to identify all active TCP connections and the specific process ID (PID) associated with each. Type the Windows command to display this.',
    options: [],
    correctAnswer: 'netstat -ano',
    explanation: 'In Windows, "netstat -ano" displays all active connections, numerical addresses, and the owning process ID.',
    weight: 10,
  },
  {
    id: 'cli_i3',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A user is reporting slow connectivity to a server in a different city. Type the command to trace the path to "10.0.50.1" and show the latency at each hop (Windows syntax).',
    options: [],
    correctAnswer: 'tracert 10.0.50.1',
    explanation: 'The tracert command in Windows sends ICMP Echo Requests with increasing TTL values to identify every router in the path.',
    weight: 10,
  },
  {
    id: 'cli_i4',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'Type the command to see the local machine\'s ARP cache to verify MAC-to-IP mappings.',
    options: [],
    correctAnswer: 'arp -a',
    explanation: 'The "arp -a" command displays the Address Resolution Protocol (ARP) table.',
    weight: 10,
  },
  {
    id: 'zta_2',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.1 Security Concepts',
    question: 'Which ZTA component is responsible for making the final decision to grant or deny access to a resource based on real-time policy evaluation?',
    options: ['Policy Decision Point (PDP)', 'Policy Enforcement Point (PEP)', 'Identity Provider (IdP)', 'SIEM'],
    correctAnswer: 'Policy Decision Point (PDP)',
    explanation: 'The PDP evaluates the access request against defined policies and context to determine if access should be permitted.',
    weight: 10,
  },
  {
    id: 'ipv6_2',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'A network administrator is configuring a router to encapsulate IPv6 packets inside IPv4 headers to allow them to cross an IPv4-only core network. This is known as:',
    options: ['Tunneling', 'Dual Stack', 'NAT-PT', 'Static Mapping'],
    correctAnswer: 'Tunneling',
    explanation: 'Tunneling encapsulates one protocol into another to cross incompatible network segments.',
    weight: 10,
  },
  // --- SYSLOG PBQS ---
  {
    id: 'log1',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A network administrator is investigating a report that a critical server is intermittently losing connection to the network. Analyze the switch logs below and identify the line that explains why the server is disconnected.',
    options: [],
    logData: [
      'May 19 04:12:01.234: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up',
      'May 19 04:12:05.102: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to up',
      'May 19 04:15:33.882: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to down',
      'May 19 04:15:38.221: %PM-4-ERR_DISABLE: psecure-violation error detected on Gi0/1, putting Gi0/1 in err-disable state',
      'May 19 04:15:38.225: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to down'
    ],
    correctLogIndex: 3,
    correctAnswer: '3',
    explanation: 'The log reflects an "err-disable" status caused by a port security violation. This happens when the switch detects more MAC addresses than allowed on a single port.',
    weight: 10,
  },
  {
    id: 'log2',
    type: 'syslog',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'An external consultant is auditing the corporate firewall. Users are complaining they cannot access the new web portal on 10.50.2.100. Identify the ACL entry causing the traffic drop.',
    options: [],
    logData: [
      'access-list 101 permit tcp 192.168.1.0 0.0.0.255 any eq 80',
      'access-list 101 permit tcp 192.168.1.0 0.0.0.255 any eq 443',
      'access-list 101 deny tcp any host 10.50.2.100 eq 443',
      'access-list 101 permit udp any any eq 53',
      'access-list 101 permit icmp any any'
    ],
    correctLogIndex: 2,
    correctAnswer: '2',
    explanation: 'The explicit "deny tcp any host 10.50.2.100 eq 443" entry blocks all HTTPS traffic destined for that specific server.',
    weight: 10,
  },
  {
    id: 'log3',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.3 Routing Issues',
    question: 'A router is failing to reach a remote network (172.16.20.0/24). Examine the routing table and identify the entry that conflicts with the intended destination.',
    options: [],
    logData: [
      'C    192.168.1.0/24 is directly connected, GigabitEthernet0/0',
      'L    192.168.1.1/32 is directly connected, GigabitEthernet0/0',
      'S    172.16.20.0/24 [1/0] via 10.0.0.5',
      'S    172.16.20.0/24 [1/5] is directly connected, Null0',
      'C    10.0.0.0/30 is directly connected, Serial0/0/0'
    ],
    correctLogIndex: 3,
    correctAnswer: '3',
    explanation: 'The entry "172.16.20.0/24 [1/5] is directly connected, Null0" is a static route redirecting all traffic for that subnet to the Null0 interface (the bit bucket), effectively dropping it.',
    weight: 10,
  },
  {
    id: 'log4',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Wireless Issues',
    question: 'A user is unable to connect to the "Internal-Secure" SSID. Review the RADIUS server logs and identify why the authentication is failing.',
    options: [],
    logData: [
      '2026-05-19 14:02:01: Sending Access-Request to 10.1.1.5:1812',
      '2026-05-19 14:02:01: User "jdoe" authenticated via EAP-TLS',
      '2026-05-19 14:10:45: Sending Access-Request to 10.1.1.5:1812',
      '2026-05-19 14:10:46: Received Access-Reject for User "admin_test": Shared secret mismatch',
      '2026-05-19 14:12:30: Sending Access-Request to 10.1.1.5:1812',
      '2026-05-19 14:12:31: User "guest" authenticated via PEAP-MSCHAPv2'
    ],
    correctLogIndex: 3,
    correctAnswer: '3',
    explanation: 'The log clearly states "Shared secret mismatch", which indicates the password/secret configured on the Wireless LAN Controller (WLC) does not match the secret on the RADIUS server.',
    weight: 10,
  },
  {
    id: 'log5',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Physical Issues',
    question: 'A network technician is monitoring a core switch. SFP module performance is dropping. Identify the line indicating a hardware-level optical failure.',
    options: [],
    logData: [
      'GigabitEthernet1/0/1 is up, line protocol is up (connected)',
      'Full-duplex, 1000Mb/s, link type is auto, media type is 1000BaseSX',
      'Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0',
      'Received 124312384 bytes, 214151 unicasts, 0 runts, 0 giants, 0 throttles',
      '0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored',
      'Optical Receive Power: -40.2 dBm (Low Alarm Threshold: -30.0 dBm)',
      'Last clearing of "show interface" counters never'
    ],
    correctLogIndex: 5,
    correctAnswer: '5',
    explanation: 'The optical receive power of -40.2 dBm is well below the low alarm threshold of -30.0 dBm, indicating a "low light" condition, likely due to a dirty connector or failing fiber.',
    weight: 10,
  },
  {
    id: 'scen7',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.1 OSI Layers',
    question: 'A network administrator is troubleshooting an issue where a server is responding to ICMP echo requests (pings) but users cannot connect to a web application running on port 443. At which OSI layer is the problem MOST likely occurring?',
    options: ['Layer 3', 'Layer 4', 'Layer 2', 'Layer 1'],
    correctAnswer: 'Layer 4',
    explanation: 'Correct: Since ping (ICMP, Layer 3) works, the network path is functional. The failure to connect to port 443 (TCP, Layer 4) suggests an issue at the Transport layer, such as a blocked port or misconfigured service.\n\nIncorrect: Layer 3 is functional as pings respond. Layers 1 and 2 are functional as physical and link-level connectivity is required for ping.',
    weight: 10,
  },
  {
    id: 'scen8',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.2 Security Attacks',
    question: 'An attacker is sending unsolicited ARP messages to a switch, mapping the IP address of the default gateway to the attacker\'s own MAC address. What type of attack is this?',
    options: ['ARP Poisoning', 'DNS Spoofing', 'DDoS', 'On-path Attack'],
    correctAnswer: 'ARP Poisoning',
    explanation: 'Correct: ARP Poisoning (or ARP Spoofing) involves sending fraudulent ARP messages to a local network to associate the attacker\'s MAC address with a legitimate IP address, allowing for traffic interception.\n\nIncorrect: DNS Spoofing affects name resolution. DDoS is a volumetric attack. On-path is a general term, but ARP poisoning is the specific mechanism here.',
    weight: 10,
  },
  {
    id: 'ac3',
    type: 'acronym',
    domain: '2.0 Implementation',
    objective: '2.3 Wireless Tech',
    question: 'Acronym: A technician is installing a wireless bridge that operates in both the 2.4GHz and 5GHz bands. Which Wi-Fi standard specifically introduced MIMO to improve throughput?',
    options: ['802.11n', '802.11ac', '802.11g', '802.11a'],
    correctAnswer: '802.11n',
    explanation: 'Correct: 802.11n (Wi-Fi 4) was the first standard to introduce MIMO (Multiple Input, Multiple Output). It also supported both the 2.4GHz and 5GHz bands.\n\nIncorrect: 802.11ac (Wi-Fi 5) introduced MU-MIMO. 802.11g/a are older standards.',
    weight: 10,
  },
  {
    id: 'ac4',
    type: 'acronym',
    domain: '1.0 Concepts',
    objective: '1.3 IPv6 Addressing',
    question: 'Acronym: Your organization needs to automatically assign IPv6 addresses to clients without using a stateful DHCPv6 server. Which mechanism allows for this?',
    options: ['SLAAC', 'NAT64', '6to4', 'Dual Stack'],
    correctAnswer: 'SLAAC',
    explanation: 'Correct: SLAAC (Stateless Address Autoconfiguration) allows a device to configure its own IPv6 address based on the prefix advertised by the router (RA messages).\n\nIncorrect: NAT64 is for protocol translation. 6to4 is a tunneling mechanism. Dual Stack is running both IPv4 and IPv6.',
    weight: 10,
  },
  {
    id: 'scen9',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.2 Switching',
    question: 'Several switches are connected in a loop to provide redundancy. Which protocol should be enabled to prevent broadcast storms while maintaining the redundant paths?',
    options: ['STP', 'OSPF', 'BGP', 'LLDP'],
    correctAnswer: 'STP',
    explanation: 'Correct: Spanning Tree Protocol (STP) detects redundant paths and logically disables ports to prevent loops, while allowing the paths to reactive if a link fails.\n\nIncorrect: OSPF is a Layer 3 routing protocol. BGP is for Inter-domain routing. LLDP is a discovery protocol.',
    weight: 10,
  },
  {
    id: 'scen10',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'A security engineer wants to ensure that only authenticated devices can access the local Ethernet network. Which standard should be implemented on the switch ports?',
    options: ['802.1X', '802.1Q', '802.3ad', '802.11ac'],
    correctAnswer: '802.1X',
    explanation: 'Correct: 802.1X is the standard for port-based network access control (PNAC). It requires users or devices to authenticate before the switch port is opened.\n\nIncorrect: 802.1Q is for VLAN tagging. 802.3ad is for Link Aggregation (LACP). 802.11ac is a Wi-Fi standard.',
    weight: 10,
  },
  {
    id: 'scen11',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.4 Protocols',
    question: 'An administrator needs to securely manage a remote switch and requires an encrypted session. Which protocol should be used instead of Telnet?',
    options: ['SSH', 'SNMPv2', 'HTTP', 'RDP'],
    correctAnswer: 'SSH',
    explanation: 'Correct: SSH (Secure Shell) provides encrypted remote login sessions. Telnet sends all traffic (including passwords) in plaintext.\n\nIncorrect: SNMPv2 is for monitoring but lacks strong security (unlike v3). HTTP is unencrypted web. RDP is for remote desktop on Windows, not typically for CLI management of switches.',
    weight: 10,
  },
  {
    id: 'scen12',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.2 High Availability',
    question: 'A data center design requires a protocol that allows a group of routers to share a single virtual IP address as a default gateway. If the master router fails, another router automatically takes over. Which protocol provides this?',
    options: ['VRRP', 'LACP', 'STP', 'BGP'],
    correctAnswer: 'VRRP',
    explanation: 'Correct: VRRP (Virtual Router Redundancy Protocol) creates a virtual router that serves as the default gateway, providing redundancy among a group of physical routers.\n\nIncorrect: LACP is for link aggregation. STP is for loop prevention. BGP is for routing.',
    weight: 10,
  },
  {
    id: 'sub6',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'Which of the following IPv6 addresses is a link-local address?',
    options: ['fe80::1', '2001:db8::1', 'fc00::1', '::1'],
    correctAnswer: 'fe80::1',
    explanation: 'Correct: IPv6 link-local addresses always start with the prefix fe80::/10. They are used for communication within a single network segment.\n\nIncorrect: 2001:db8:: is a global unicast address. fc00:: is unique local. ::1 is the loopback address.',
    weight: 10,
  },
  {
    id: 'ac5',
    type: 'acronym',
    domain: '1.0 Concepts',
    objective: '1.7 Cloud Concepts',
    question: 'Acronym: Your company is using a cloud service where you are responsible for managing the OS, middleware, and applications, while the provider manages the physical servers and virtualization. Which service model is this?',
    options: ['IaaS', 'PaaS', 'SaaS', 'NaaS'],
    correctAnswer: 'IaaS',
    explanation: 'Correct: Infrastructure as a Service (IaaS) provides virtualized computing resources (servers, storage) over the internet. You manage the OS and everything above it.\n\nIncorrect: PaaS manages the OS and runtime. SaaS manages the entire application.',
    weight: 10,
  },
  {
    id: 'multi3',
    type: 'multi-select',
    domain: '1.0 Concepts',
    objective: '1.4 Ports & Protocols',
    question: 'A technician is setting up a new email server. Which of the following ports should be used for SECURE incoming and outgoing email? (Select TWO).',
    options: ['993', '465', '110', '25', '143', '587'],
    correctAnswer: ['993', '465'],
    explanation: 'Correct: Port 993 is IMAPS (secure IMAP). Port 465 is SMTPS (secure SMTP over SSL/TLS).\n\nIncorrect: 110 (POP3), 25 (SMTP), and 143 (IMAP) are all unencrypted.',
    weight: 10,
  },
  {
    id: 'scen13',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.2 Security Attacks',
    question: 'An organization is hit by an attack that uses a botnet to overwhelm its web servers with millions of illegitimate HTTP requests. What type of attack is this?',
    options: ['DDoS', 'On-path', 'Social Engineering', 'Dictionary Attack'],
    correctAnswer: 'DDoS',
    explanation: 'Correct: Distributed Denial of Service (DDoS) uses many compromised systems (a botnet) to flood a target with traffic, making it unavailable to legitimate users.\n\nIncorrect: On-path intercepts traffic. Social engineering targets people. Dictionary attack targets passwords.',
    weight: 10,
  },
  {
    id: 'scen14',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.2 WAN Tech',
    question: 'A company needs to connect two branch offices using a dedicated, high-latency satellite link. Which technology is MOST likely to be used to encapsulate multiple protocols over this link?',
    options: ['PPP', 'ATM', 'Frame Relay', 'ISDN'],
    correctAnswer: 'PPP',
    explanation: 'Correct: Point-to-Point Protocol (PPP) is a Layer 2 protocol used to establish a direct connection between two nodes, commonly used in WAN links for protocol encapsulation.\n\nIncorrect: ATM and Frame Relay are older packet/cell switching technologies. ISDN is for digital telephone lines.',
    weight: 10,
  },
  {
    id: 'ts6',
    type: 'architect',
    domain: '5.4 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A technician is using a tone generator and probe to find a specific wire in a crowded server room. What is this tool combo often called?',
    options: ['Fox and Hound', 'TDR', 'OTDR', 'Loopback Plug'],
    correctAnswer: 'Fox and Hound',
    explanation: 'Correct: A tone generator and probe is colloquially known as a "Fox and Hound" tool, used for tracing cables.\n\nIncorrect: TDR/OTDR find breaks in cables. A loopback plug is for port testing.',
    weight: 10,
  },
  {
    id: 'sub7',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'An interface has an IP address of 10.0.0.1 and a subnet mask of 255.255.248.0. What is the broadcast address of this network?',
    options: ['10.0.7.255', '10.0.15.255', '10.0.0.255', '10.0.255.255'],
    correctAnswer: '10.0.7.255',
    explanation: 'Correct: 248 in the 3rd octet means the increment is 8 (256-248). The network starts at 10.0.0.0 and ends at 10.0.7.255.',
    weight: 10,
  },
  {
    id: 'deep16',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Infrastructure',
    question: 'A company is implementing a software-defined storage solution that pools together local storage from multiple servers into a single shared storage resource. Which technology is this?',
    options: ['vSAN', 'iSCSI SAN', 'NFS', 'Object Storage'],
    correctAnswer: 'vSAN',
    explanation: 'Correct: vSAN (Virtual SAN) is a software-defined storage (SDS) solution that aggregates local disks across a cluster to create a shared data store.\n\nIncorrect: iSCSI SAN uses a dedicated network. NFS is file-level. Object storage is for unstructured data.',
    weight: 10,
  },
  {
    id: 'deep17',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.4 Physical Security',
    question: 'An organization wants to implement a physical security control that prevents "tailgating" by allowing only one person to enter at a time through a secure vestibule. What is this called?',
    options: ['Mantrap', 'Bollard', 'Biometric Lock', 'Motion Sensor'],
    correctAnswer: 'Mantrap',
    explanation: 'Correct: A mantrap (or security vestibule) is a small room with two doors. One door must close and lock before the second door can be opened, effectively preventing tailgating.\n\nIncorrect: Bollards prevent vehicle entry. Biometrics are for auth. Motion sensors detect presence.',
    weight: 10,
  },
  {
    id: 'ac6',
    type: 'acronym',
    domain: '3.0 Operations',
    objective: '3.2 High Availability',
    question: 'Acronym: Your cloud provider guarantees that their service will be available 99.999% of the time in the contract. What is this document called?',
    options: ['SLA', 'SOW', 'MOU', 'NDA'],
    correctAnswer: 'SLA',
    explanation: 'Correct: A Service Level Agreement (SLA) is a contract between a service provider and a customer that defines the level of service, including uptime and performance metrics.\n\nIncorrect: SOW defines work tasks. MOU is a formal agreement. NDA is for confidentiality.',
    weight: 10,
  },
  {
    id: 'ac7',
    type: 'acronym',
    domain: '2.0 Implementation',
    objective: '2.4 Wireless',
    question: 'Acronym: A technician is using a standard that allows for multiple wireless access points to be managed by a single centralized device. Which protocol is often used for this management?',
    options: ['LWAPP', 'SNMP', 'LLDP', 'ICMP'],
    correctAnswer: 'LWAPP',
    explanation: 'Correct: Lightweight Access Point Protocol (LWAPP) or CAPWAP are used to manage lightweight APs from a centralized Wireless LAN Controller (WLC).\n\nIncorrect: SNMP is for general monitoring. LLDP is for discovery. ICMP is for pings.',
    weight: 10,
  },
  {
    id: 'sub8',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'You have been assigned the IP block 192.168.50.0/24. You need to create subnets that can support at least 12 hosts each. What is the most efficient prefix length?',
    options: ['/28', '/27', '/29', '/26'],
    correctAnswer: '/28',
    explanation: 'Correct: A /28 provides 2^4 = 16 total addresses, which gives 14 usable hosts (16-2). This is the smallest subnet that fits 12 hosts.\n\nIncorrect: /29 only has 6 usable hosts. /27 has 30, which is less efficient.',
    weight: 10,
  },
  {
    id: 'scen15',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A network engineer is troubleshooting a fiber optic link that is down. The OTDR report shows a high reflection and loss at exactly 50 meters from the source. What does this MOST likely indicate?',
    options: ['Dirty or damaged connector', 'Fiber attenuation', 'Bending radius violation', 'Crosstalk'],
    correctAnswer: 'Dirty or damaged connector',
    explanation: 'Correct: A sharp spike in reflection and loss at a specific point usually indicates a physical interface issue, such as a dirty, scratched, or improperly seated connector.\n\nIncorrect: Attenuation happens over length. Bending causes loss but less reflection. Crosstalk is an electrical (copper) issue.',
    weight: 10,
  },
  {
    id: 'multi4',
    type: 'multi-select',
    domain: '1.0 Concepts',
    objective: '1.1 OSI Model',
    question: 'Which of the following protocols operate at the Application Layer (Layer 7) of the OSI model? (Select TWO).',
    options: ['DNS', 'SMTP', 'TCP', 'IP', 'Ethernet', 'BGP'],
    correctAnswer: ['DNS', 'SMTP'],
    explanation: 'Correct: DNS and SMTP are Application Layer protocols. \n\nIncorrect: TCP is Transport (L4). IP is Network (L3). Ethernet is Data Link (L2).',
    weight: 10,
  },
  {
    id: 'scen16',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.2 Security Attacks',
    question: 'An employee receives an email that appears to be from the CEO, asking for an urgent wire transfer to a new vendor. The email address is slightly misspelled. What type of attack is this?',
    options: ['Business Email Compromise (BEC)', 'Vishing', 'Whaling', 'Pharming'],
    correctAnswer: 'Business Email Compromise (BEC)',
    explanation: 'Correct: BEC is a specific type of spear phishing where an attacker impersonates a high-level executive to defraud a company.\n\nIncorrect: Whaling is general high-level phishing. Vishing is voice-based. Pharming redirects traffic to fake sites via DNS.',
    weight: 10,
  },
  {
    id: 'scen17',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'A technician is installing a new fiber link and needs a connector that uses a thread-and-screw mechanism to stay securely attached in high-vibration environments. Which connector should they use?',
    options: ['FC', 'LC', 'ST', 'SC'],
    correctAnswer: 'FC',
    explanation: 'Correct: FC (Ferrule Connector) uses a threaded body to screw onto the interface, making it ideal for high-vibration environments.\n\nIncorrect: ST uses a bayonet mount. LC and SC use push-pull or latch mechanisms.',
    weight: 10,
  },
  {
    id: 'scen18',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.4 Wireless',
    question: 'Your organization is deploying a wireless network that must support the 6GHz band. Which Wi-Fi standard should be implemented?',
    options: ['Wi-Fi 6E', 'Wi-Fi 6', 'Wi-Fi 5', 'Wi-Fi 4'],
    correctAnswer: 'Wi-Fi 6E',
    explanation: 'Correct: Wi-Fi 6E (802.11ax) extended the standard into the 6GHz band, providing more spectrum and less interference.\n\nIncorrect: Wi-Fi 6 only covers 2.4GHz and 5GHz. Wi-Fi 5 (ac) and Wi-Fi 4 (n) are older.',
    weight: 10,
  },
  {
    id: 'ac8',
    type: 'acronym',
    domain: '4.0 Security',
    objective: '4.3 Security',
    question: 'Acronym: Your firewall is configured to perform deep packet inspection to identify and block traffic based on specific application signatures. What is this type of device called?',
    options: ['NGFW', 'UTM', 'WAF', 'DLP'],
    correctAnswer: 'NGFW',
    explanation: 'Correct: A Next-Generation Firewall (NGFW) goes beyond traditional port/IP filtering by including application awareness and deep packet inspection (DPI).\n\nIncorrect: UTM includes multiple security services. WAF is for web apps specifically. DLP is for data loss prevention.',
    weight: 10,
  },
  {
    id: 'scen19',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.1 Procedures',
    question: 'Before performing a major upgrade on the core router, a network engineer documents the current state including config, light levels, and routing tables. What is this documentation called?',
    options: ['Baseline', 'As-built', 'SOP', 'SLA'],
    correctAnswer: 'Baseline',
    explanation: 'Correct: A baseline documents the normal operating state of a system, which is critical to compare against if issues arise after a change.\n\nIncorrect: As-built is how it was installed. SOP is a procedure. SLA is a contract.',
    weight: 10,
  },
  {
    id: 'sub9',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IPv4',
    question: 'What is the binary representation of the decimal value 192?',
    options: ['11000000', '10101000', '11110000', '10000000'],
    correctAnswer: '11000000',
    explanation: 'Correct: 192 is 128 + 64, which in 8-bit binary is 11000000.',
    weight: 10,
  },
  {
    id: 'scen20',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Issues',
    question: 'A user reports that they have a "Limited connectivity" warning. Their IP address starts with 169.254.x.x. What does this indicate?',
    options: ['DHCP failure/APIPA', 'Duplicate IP', 'Bad Gateway', 'Expired Lease'],
    correctAnswer: 'DHCP failure/APIPA',
    explanation: 'Correct: 169.254.0.0/16 is the APIPA range, which Windows assigns automatically when it cannot reach a DHCP server.\n\nIncorrect: Duplicate IP usually causes a specific error. Bad gateway affects routing. Expired lease would lead to APIPA if not renewed.',
    weight: 10,
  },
  {
    id: 'multi5',
    type: 'multi-select',
    domain: '1.0 Concepts',
    objective: '1.4 Protocols',
    question: 'A technician is configuring a server and needs to ensure both time synchronization and name resolution are functional. Which ports should be allowed? (Select TWO).',
    options: ['123', '53', '161', '443', '22', '389'],
    correctAnswer: ['123', '53'],
    explanation: 'Correct: Port 123 is NTP (time sync). Port 53 is DNS (name resolution).\n\nIncorrect: 161 (SNMP), 443 (HTTPS), 22 (SSH), 389 (LDAP).',
    weight: 10,
  },
  {
    id: 'scen21',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.2 WAN',
    question: 'An organization wants to connect all its branches in a flat Layer 2 network over a provider\'s MPLS core. Which technology provides this "Pseudo-wire" service?',
    options: ['VPLS', 'MPLS L3 VPN', 'DMVPN', 'GRE'],
    correctAnswer: 'VPLS',
    explanation: 'Correct: VPLS (Virtual Private LAN Service) allows multiple sites to share an Ethernet broadcast domain over an MPLS network.\n\nIncorrect: L3 VPN works at the network layer. DMVPN is Cisco specific tunnel. GRE is simple encapsulation.',
    weight: 10,
  },
  {
    id: 'scen22',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.1 Concepts',
    question: 'You are implementing a security strategy that uses firewalls, AV software, MFA, and physical locks together. What is this concept known as?',
    options: ['Defense in Depth', 'Hardeninig', 'Least Privilege', 'Segmentation'],
    correctAnswer: 'Defense in Depth',
    explanation: 'Correct: Defense in Depth (Layered Security) involves using multiple security controls at different levels to protect an asset.\n\nIncorrect: Hardening is securing a single system. Least privilege is access control. Segmentation is network division.',
    weight: 10,
  },
  {
    id: 'scen23',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Infrastructure',
    question: 'A cloud architect is designing a network to support heavy virtual machine migrations and server-to-server database replication within the same facility. Which of the following traffic flows and architectures is MOST appropriate?',
    options: ['East-West traffic using a Spine-and-Leaf topology', 'North-South traffic using a Three-Tier Hierarchical model', 'North-South traffic using a Hub-and-Spoke topology', 'East-West traffic using a Ring topology'],
    correctAnswer: 'East-West traffic using a Spine-and-Leaf topology',
    explanation: {
      whyCorrect: "East-west traffic refers to data transfer within a data center (server-to-server). A Spine-and-Leaf topology provides the low-latency, high-bandwidth mesh required for this, especially for VM migrations (vMotion/Live Migration).",
      whyWrong: [
        { option: "North-South traffic using a Three-Tier Hierarchical model", reason: "North-south traffic refers to traffic entering/leaving the data center. Three-tier is older and less efficient for massive east-west flows." },
        { option: "North-South traffic using a Hub-and-Spoke topology", reason: "Hub-and-Spoke creates tight bottlenecks and is usually for WAN connections, not high-speed server migrations." },
        { option: "East-West traffic using a Ring topology", reason: "Ring topologies are legacy (Token Ring/FDDI) and are never used for high-performance data center fabric designs." }
      ]
    },
    weight: 10,
  },
  {
    id: 'scen24',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'A security engineer is upgrading the corporate WLAN to mitigate offline dictionary attacks against wireless handshakes. The new implementation must drop the use of Pre-Shared Keys (PSK). Which of the following should be implemented?',
    options: ['WPA3 using SAE (Simultaneous Authentication of Equals)', 'WPA3 using AES-CCMP', 'WPA2 Enterprise with TKIP', 'WPA3 using OWE (Opportunistic Wireless Encryption)'],
    correctAnswer: 'WPA3 using SAE (Simultaneous Authentication of Equals)',
    explanation: {
      whyCorrect: "WPA3 replaces Pre-Shared Keys with SAE (Simultaneous Authentication of Equals). SAE provides Forward Secrecy and makes offline dictionary attacks much harder by requiring an interactive exchange for each authentication attempt.",
      whyWrong: [
        { option: "WPA3 using AES-CCMP", reason: "AES-CCMP is the encryption algorithm. While WPA3 uses it, SAE is the specific mechanism that solves the handshake/dictionary attack problem." },
        { option: "WPA2 Enterprise with TKIP", reason: "WPA2 Enterprise uses 802.1X/RADIUS, not PSK, but TKIP is legacy/insecure and WPA2 is still vulnerable to some handshake captures." },
        { option: "WPA3 using OWE", reason: "OWE (Opportunistic Wireless Encryption) provides encryption for open guest networks, but it doesn't use passwords at all." }
      ]
    },
    weight: 10,
  },
  {
    id: 'sub10',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'A technician connects Workstation A (IP: 10.0.0.14/28) and Workstation B (IP: 10.0.0.22/28) to the same unmanaged Layer 2 switch. The workstations cannot ping each other. What is the MOST likely cause?',
    options: ['The workstations are in different subnets and require a Layer 3 device to route traffic', 'The switch requires 802.1Q VLAN tagging to be configured', 'The workstations are both in the same collision domain', 'A crossover cable is required between the workstations'],
    correctAnswer: 'The workstations are in different subnets and require a Layer 3 device to route traffic',
    explanation: {
      whyCorrect: "A /28 subnet has a block size of 16. Subnet 1 covers 10.0.0.0 - 10.0.0.15 (hosts .1-.14). Subnet 2 covers 10.0.0.16 - 10.0.0.31 (hosts .17-.30). Because .14 and .22 are in logically separate subnets, they cannot communicate on Layer 2 without a Layer 3 gateway.",
      whyWrong: [
        { option: "The switch requires 802.1Q VLAN tagging to be configured", reason: "Unmanaged switches ignore VLAN tags; even on a managed switch, the primary issue is the IP subnet mismatch." },
        { option: "The workstations are both in the same collision domain", reason: "Switches create separate collision domains per port. Even if they were in the same domain, the IP routing would still fail." },
        { option: "A crossover cable is required between the workstations", reason: "Modern switches use Auto-MDIX to auto-detect cable types; the hardware layer is likely fine since link lights were verified." }
      ]
    },
    weight: 10,
  },
  {
    id: 'ha3',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.2 High Availability',
    question: 'An enterprise network uses two core routers. Router A actively handles all traffic, while Router B sits idle, monitoring Router A via keepalives. If Router A fails, Router B takes over the virtual IP gateway. What specific architecture is this?',
    options: ['Active-Passive using FHRP (First Hop Redundancy Protocol)', 'Active-Active using MLAG', 'Active-Passive using LACP', 'Active-Passive using STP'],
    correctAnswer: 'Active-Passive using FHRP (First Hop Redundancy Protocol)',
    explanation: {
      whyCorrect: "FHRPs like HSRP (Hot Standby Router Protocol) or VRRP allow multiple routers to present a single 'Virtual IP' to clients. In Active-Passive, only one router forwards data while the other waits for a heartbeat failure.",
      whyWrong: [
        { option: "Active-Active using MLAG", reason: "MLAG allows multiple physical links to be treated as one logical link between two switches, not specifically for gateway redundancy." },
        { option: "Active-Passive using LACP", reason: "LACP is for Link Aggregation (bonding) of multiple cables between two fixed points, not for router gateway failover." },
        { option: "Active-Passive using STP", reason: "Spanning Tree Protocol (STP) prevents loops at Layer 2; it doesn't manage Layer 3 gateway IP redundancy." }
      ]
    },
    weight: 10,
  },
  {
    id: 'scen25',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'A technician is connecting two switches inside the same server rack that are 2 meters apart. To minimize latency and cost without using fiber optics, which of the following cabling types should be used?',
    options: ['DAC (Direct Attach Copper) Twinaxial cable', 'Cat 6a UTP Patch cable', 'Single-mode Fiber with LC connectors', 'InfiniBand cable'],
    correctAnswer: 'DAC (Direct Attach Copper) Twinaxial cable',
    explanation: {
      whyCorrect: "Direct Attach Copper (DAC) cables are Twinaxial cables with factory-integrated SFP+ transceivers on both ends. They are the most cost-effective and lowest-latency choice for very short distances (under 7m).",
      whyWrong: [
        { option: "Cat 6a UTP Patch cable", reason: "While Cat6a supports 10Gbps, it requires Base-T transceivers which are more expensive and consume more power than DAC cables." },
        { option: "Single-mode Fiber with LC connectors", reason: "SMF is for long distances (kilometers). Using it for 2 meters is overkill and requires two separate, expensive SFP+ transceivers." },
        { option: "InfiniBand cable", reason: "InfiniBand is a separate high-performance computing architecture, not typically used for standard Ethernet switch-to-switch links." }
      ]
    },
    weight: 10,
  },
  {
    id: 'ts7',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.4 Troubleshooting Model',
    question: 'A user reports they cannot access the local intranet server. The technician verifies the user\'s PC has a link light and an IP address of 192.168.1.105. What should the technician do NEXT?',
    options: ['Ping the local default gateway', 'Ping the intranet server', 'Run an ipconfig /release and renew', 'Reboot the local switch'],
    correctAnswer: 'Ping the local default gateway',
    explanation: {
      whyCorrect: "The logical next step in connectivity troubleshooting is checking the Default Gateway. If you can ping the gateway but not the server, the problem is likely on the other side of the router.",
      whyWrong: [
        { option: "Ping the intranet server", reason: "Pinging the destination directly skips the hop-by-hop verification. If it fails, you won't know if the router or the server is the bottleneck." },
        { option: "Run an ipconfig /release and renew", reason: "The technician already verified the PC has a valid 192.168.1.x address, so DHCP is currently working correctly." },
        { option: "Reboot the local switch", reason: "Rebooting the switch affects all users; the link light indicates Layer 1 is fine, so checking routing is more targeted than rebooting hardware." }
      ]
    },
    weight: 10,
  }
];
