import { Question } from './types';

export const questions: Question[] = [
  // --- DOMAIN 1.0: NETWORKING CONCEPTS (23%) ---
  {
    id: 'scen1',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.8 Modern Envs',
    question: 'A network administrator is designing a highly scalable data center fabric. They need to provide Layer 2 connectivity over a Layer 3 spine-leaf architecture while allowing for over 16 million segments. Which technology is BEST suited for this requirement?',
    options: ['VXLAN', 'STP', 'VLAN', '802.1Q'],
    correctAnswer: 'VXLAN',
    explanation: 'Correct: VXLAN (Virtual Extensible LAN) is the industry standard for large data centers. It uses a 24-bit VNI (VXLAN Network Identifier), which supports over 16 million unique segments, far exceeding the 4,096-segment limit of traditional 802.1Q VLANs.\n\nIncorrect: STP (Spanning Tree Protocol) is for loop prevention. VLANs are limited to 4,096 IDs. 802.1Q is the standard trunking protocol, but doesn\'t provide the scale of VXLAN.',
    weight: 10,
  },
  {
    id: 'scen2',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.8 Modern Envs',
    question: 'An organization needs to optimize cloud application performance for branch offices by dynamically routing traffic based on real-time link quality and application requirements. Which solution should be implemented?',
    options: ['SD-WAN', 'BGP', 'Site-to-Site VPN', 'Static Routing'],
    correctAnswer: 'SD-WAN',
    explanation: 'Correct: SD-WAN (Software-Defined Wide Area Network) provides dynamic path selection (DPS), allowing traffic to be routed over MPLS, Broadband, or LTE based on performance metrics like jitter and latency.\n\nIncorrect: BGP is for path exchange between AS. Site-to-Site VPN provides a tunnel but doesn\'t typically include application-aware dynamic routing. Static routing is manual and non-dynamic.',
    weight: 10,
  },
  {
    id: 'multi1',
    type: 'multi-select',
    domain: '1.0 Concepts',
    objective: '1.4 Ports & Protocols',
    question: 'A security engineer is configuring a stateful firewall. Which of the following ports should be allowed to facilitate secure remote administration and secure file transfer? (Select TWO).',
    options: ['22', '23', '443', '445', '990'],
    correctAnswer: ['22', '990'],
    explanation: 'Correct: Port 22 is used for SSH (secure administration) and SFTP. Port 990 is used for FTPS (FTP over TLS/SSL) implicit mode.\n\nIncorrect: Port 23 is Telnet (plaintext). Port 443 is HTTPS. Port 445 is SMB/AD.',
    weight: 10,
  },

  // --- DOMAIN 2.0: NETWORK IMPLEMENTATION (20%) ---
  {
    id: 'scen3',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.1 Routing Technologies',
    question: 'You are configuring a router for a large enterprise. You need to use an interior gateway protocol that provides fast convergence and supports large-scale hierarchies using areas. Which protocol is the BEST choice?',
    options: ['OSPF', 'BGP', 'RIPv2', 'EGP'],
    correctAnswer: 'OSPF',
    explanation: 'OSPF is a link-state IGP that uses SPF for fast convergence and supports hierarchical design through areas.',
    weight: 10,
  },
  {
    id: 'scen4',
    type: 'architect',
    domain: '2.0 Implementation',
    objective: '2.1 Routing Technologies',
    question: 'A network technician is troubleshooting a routing issue between two different Autonomous Systems. Which protocol is responsible for exchanging routing information between them?',
    options: ['BGP', 'OSPF', 'EIGRP', 'IS-IS'],
    correctAnswer: 'BGP',
    explanation: 'Border Gateway Protocol (BGP) is the standard Exterior Gateway Protocol (EGP) used to route between Autonomous Systems.',
    weight: 10,
  },

  // --- DOMAIN 3.0: NETWORK OPERATIONS (19%) ---
  {
    id: 'ac1',
    type: 'acronym',
    domain: '3.0 Operations',
    objective: '3.3 Disaster Recovery',
    question: 'Acronym: A service level agreement specifies that a critical server must be back online within 4 hours of a failure. Which metric does this represent?',
    options: ['RTO', 'RPO', 'MTBF', 'MTTR'],
    correctAnswer: 'RTO',
    explanation: 'Recovery Time Objective (RTO) defines the maximum acceptable duration of downtime.',
    weight: 10,
  },
  {
    id: 'ac2',
    type: 'acronym',
    domain: '3.0 Operations',
    objective: '3.3 Disaster Recovery',
    question: 'Acronym: Your organization performs daily backups at midnight. A catastrophic failure occurs at 10 PM. The organization realizes they have lost 22 hours of data. Which metric measures this tolerable data loss?',
    options: ['RPO', 'RTO', 'MTTF', 'MTD'],
    correctAnswer: 'RPO',
    explanation: 'Recovery Point Objective (RPO) defines the maximum age of data that can be lost from a backup.',
    weight: 10,
  },

  // --- DOMAIN 4.0: NETWORK SECURITY (14%) ---
  {
    id: 'scen5',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.1 Security Concepts',
    question: 'A CISO wants to implement a security model where no user or device is trusted by default, even if they are inside the corporate network. Which architecture should be adopted?',
    options: ['Zero Trust', 'Defense in Depth', 'De-Militarized Zone', 'Air Gapping'],
    correctAnswer: 'Zero Trust',
    explanation: 'Zero Trust architecture requires continuous verification of all subjects (users, devices, apps) regardless of their location.',
    weight: 10,
  },
  {
    id: 'scen6',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'A technician wants to prevent unauthorized laptops from connecting to a desktop Ethernet port in a lobby. Which of the following would be the MOST effective solution?',
    options: ['Port Security', 'DHCP Snooping', 'VLAN Pooling', 'IP Source Guard'],
    correctAnswer: 'Port Security',
    explanation: 'Port security allows you to restrict the MAC addresses that can connect to a physical switch port.',
    weight: 10,
  },

  // --- DOMAIN 5.0: NETWORK TROUBLESHOOTING (24%) ---
  {
    id: 'ts1',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'Users report they cannot access a shared drive. You have questioned the users and identified that only one floor is affected. You have just established a theory of probable cause. What is the NEXT step you should take?',
    options: ['Test the theory', 'Establish a plan of action', 'Verify full system functionality', 'Document findings'],
    correctAnswer: 'Test the theory',
    explanation: 'After establishing a theory of probable cause, the next step in the CompTIA methodology is to test the theory to confirm the cause.',
    weight: 10,
  },
  {
    id: 'ts2',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'You have implemented a missing routing entry on a core router and verified that users can now reach the internet. What is the FINAL step in the troubleshooting methodology?',
    options: ['Document findings', 'Perform a root cause analysis', 'Verify functionality', 'Create a new baseline'],
    correctAnswer: 'Document findings',
    explanation: 'The final step is to document findings, actions, and outcomes to provide a reference for future issues.',
    weight: 10,
  },
  {
    id: 'ts3',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'A network technician is called to fixed a connectivity issue. After identifying the problem and establishing a theory of probable cause, the technician tests the theory and confirms it is correct. Which of the following is the BEST next step?',
    options: ['Establish a plan of action to resolve the problem', 'Implement the solution immediately', 'Verify full system functionality', 'Document the verified theory'],
    correctAnswer: 'Establish a plan of action to resolve the problem',
    explanation: 'Once a theory is tested and confirmed, the next step is to establish a plan of action to resolve the problem and identify potential effects.',
    weight: 10,
  },
  {
    id: 'ts4',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'Numerous users in a branch office report they cannot access any external websites. You observe that all local resources are reachable. Which of the following should you perform FIRST?',
    options: ['Question the users to identify any changes', 'Examine the core router interface logs', 'Restart the edge gateway', 'Replace the upstream fiber patch cable'],
    correctAnswer: 'Question the users to identify any changes',
    explanation: 'The very first step in the troubleshooting methodology is to identify the problem, which starts with questioning the users and identifying symptoms/changes.',
    weight: 10,
  },
  {
    id: 'ts5',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.1 Troubleshooting Methodology',
    question: 'A technician has replaced a faulty SFP+ module on a switch and confirmed that the link light is active. What is the MOST important next step according to the CompTIA troubleshooting model?',
    options: ['Verify full system functionality', 'Implement preventive measures', 'Document the change', 'Establish a new theory'],
    correctAnswer: 'Verify full system functionality',
    explanation: 'After implementing a solution, you must verify full system functionality and, if applicable, implement preventive measures.',
    weight: 10,
  },
  {
    id: 'cli1',
    type: 'cli',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'Which command would you use to view the mapping between Layer 2 MAC addresses and Layer 3 IP addresses on a local Windows machine?',
    options: ['arp -a', 'nslookup', 'netstat -r', 'ipconfig /all'],
    correctAnswer: 'arp -a',
    explanation: 'The arp command displays the Address Resolution Protocol (ARP) table, which maps IP addresses to MAC addresses.',
    weight: 10,
  },
  {
    id: 'cli2',
    type: 'cli',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'Traffic is heavily congested on a specific VLAN. A technician wants to see the source and destination of all packets leaving a specific interface. Which tool is BEST suited for this task?',
    options: ['tcpdump', 'traceroute', 'ping', 'dig'],
    correctAnswer: 'tcpdump',
    explanation: 'tcpdump is a packet analyzer that allows for real-time capture and inspection of network traffic.',
    weight: 10,
  },
  {
    id: 'cli3',
    type: 'cli',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A user cannot reach a website by its name but can ping its IP address. Which command-line tool would be BEST to diagnose the issue?',
    options: ['nslookup', 'netstat', 'nbtstat', 'route'],
    correctAnswer: 'nslookup',
    explanation: 'nslookup is used to query DNS, which is responsible for resolving names to IP addresses.',
    weight: 10,
  },
  {
    id: 'multi2',
    type: 'multi-select',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A network engineer needs to verify the path that packets take to a remote server and check for open ports on that server. Which of the following tools should be used? (Select TWO).',
    options: ['tracert', 'nmap', 'nslookup', 'ipconfig', 'arp'],
    correctAnswer: ['tracert', 'nmap'],
    explanation: 'tracert (or traceroute) shows the path, and nmap is a powerful port scanner.',
    weight: 10,
  },
  // --- VISUAL PBQs ---
  {
    id: 'vis1',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'A network technician is repairing a high-density fiber patch panel. Which connector type is shown in the image, characterized by its "Local Connector" small form factor and push-pull latching mechanism?',
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800',
    options: ['LC', 'SC', 'ST', 'MTRJ'],
    correctAnswer: 'LC',
    explanation: 'The LC (Local Connector) is a small form factor connector that uses a 1.25mm ferrule and a tab-style locking mechanism, common in SFP modules.',
    weight: 10,
  },
  {
    id: 'vis2',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.6 Topology',
    question: 'Observe the data center layout in the image. Which topology is depicted, utilizing a non-blocking architecture that allows any leaf switch to talk to any other leaf switch via a single hop through the spine?',
    imageUrl: 'https://images.unsplash.com/photo-1551703599-6b3e8379aa8c?auto=format&fit=crop&q=80&w=800',
    options: ['Spine-and-Leaf', 'Three-tier Hierarchical', 'Mesh', 'Ring'],
    correctAnswer: 'Spine-and-Leaf',
    explanation: 'Spine-and-Leaf is a two-tier architecture where every leaf switch connects to every spine switch, providing high bandwidth and low latency.',
    weight: 10,
  },
  {
    id: 'vis3',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'A technician is interconnecting two switches in the same rack. Which specialized cable is shown, combining a Twinaxial copper cable with integrated SFP+ transceivers?',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc4b?auto=format&fit=crop&q=80&w=800',
    options: ['Twinaxial DAC', 'AOC (Active Optical)', 'Cat8 Ethernet', 'Single-Mode Fiber'],
    correctAnswer: 'Twinaxial DAC',
    explanation: 'Direct Attach Copper (DAC) cables are Twinaxial cables with factory-attached SFP+ connectors, used for short-range Top-of-Rack connections.',
    weight: 10,
  },
  {
    id: 'vis4',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'Which legacy connector type is shown, ubiquitous in older 10Base2 Ethernet networks and still used for modern CCTV coaxial connections?',
    imageUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&q=80&w=800',
    options: ['BNC', 'F-Type', 'RJ-45', 'DB-9'],
    correctAnswer: 'BNC',
    explanation: 'BNC (Bayonet Neill-Concelman) connectors are RF connectors used with coaxial cables, featuring a bayonet mount locking mechanism.',
    weight: 10,
  },
  {
    id: 'vis5',
    type: 'visual',
    domain: '1.0 Concepts',
    objective: '1.5 Physical Media',
    question: 'Identify the fiber connector shown, often called the "Subscriber Connector" or "Standard Connector," known for its square shape and push-pull mechanism.',
    imageUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?auto=format&fit=crop&q=80&w=800',
    options: ['SC', 'LC', 'ST', 'FC'],
    correctAnswer: 'SC',
    explanation: 'The SC (Subscriber Connector) uses a 2.5mm ferrule and has a push-pull latching mechanism. It is larger than the LC connector.',
    weight: 10,
  },

  // --- DEEP SYLLABUS EXPANSION ---
  {
    id: 'deep1',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Storage',
    question: 'A financial firm requires a storage solution that allows servers to access raw block-level storage over a dedicated high-speed network. Which technology should be implemented?',
    options: ['SAN (Storage Area Network)', 'NAS (Network Attached Storage)', 'Cloud Storage', 'DFS'],
    correctAnswer: 'SAN (Storage Area Network)',
    explanation: 'SAN provides block-level access to storage, appearing as local disks to the server, typically using Fibre Channel or iSCSI.',
    weight: 10,
  },
  {
    id: 'deep2',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Storage',
    question: 'An office needs a centralized file server that connects to the existing Ethernet network and provides file-level access via SMB/NFS. Which device is BEST?',
    options: ['NAS', 'SAN', 'vSAN', 'Tape Drive'],
    correctAnswer: 'NAS',
    explanation: 'NAS (Network Attached Storage) provides file-level storage services to other devices on the network, typically over standard Ethernet.',
    weight: 10,
  },
  {
    id: 'deep3',
    type: 'multi-select',
    domain: '1.0 Concepts',
    objective: '1.4 Ports & Protocols',
    question: 'A systems administrator is hardening a directory services environment. Which ports should be allowed to support encrypted directory lookups and VoIP session initiation? (Select TWO).',
    options: ['636', '5061', '389', '5060', '1433'],
    correctAnswer: ['636', '5061'],
    explanation: 'Port 636 is LDAPS (LDAP over SSL/TLS). Port 5061 is SIP over TLS (secure).',
    weight: 10,
  },
  {
    id: 'deep4',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.4 DNS Records',
    question: 'You are adding an IPv6 record for a new web server in the corporate DNS zone. Which record type should you create?',
    options: ['AAAA', 'A', 'CNAME', 'PTR'],
    correctAnswer: 'AAAA',
    explanation: 'AAAA records map a hostname to an IPv6 address. (A records map to IPv4).',
    weight: 10,
  },
  {
    id: 'deep5',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.4 DNS Records',
    question: 'A technician needs to create a DNS alias so that "shop.example.com" points to "server1.example.com". Which record type is required?',
    options: ['CNAME', 'A', 'MX', 'TXT'],
    correctAnswer: 'CNAME',
    explanation: 'CNAME (Canonical Name) records are used to create aliases for existing A records.',
    weight: 10,
  },
  {
    id: 'deep6',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.4 DNS Records',
    question: 'An administrator needs to perform a reverse lookup to find the hostname associated with a specific IP address. Which DNS record is queried?',
    options: ['PTR', 'A', 'NS', 'SOA'],
    correctAnswer: 'PTR',
    explanation: 'PTR (Pointer) records facilitate reverse DNS lookups, mapping an IP address to a hostname.',
    weight: 10,
  },
  {
    id: 'deep7',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'An organization needs a solution that can automatically block malicious traffic in real-time as it traverses the network perimeter. Which device is MOST suitable?',
    options: ['IPS', 'IDS', 'Syslog Server', 'Load Balancer'],
    correctAnswer: 'IPS',
    explanation: 'An Intrusion Prevention System (IPS) is placed inline and can actively block or drop malicious traffic, whereas an IDS is out-of-band and only alerts.',
    weight: 10,
  },
  {
    id: 'deep8',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A switch interface is reporting a high number of CRC errors. Which of the following is the MOST likely cause?',
    options: ['Faulty cable or interference', 'Duplex mismatch', 'VLAN tagging error', 'Routing loop'],
    correctAnswer: 'Faulty cable or interference',
    explanation: 'Cyclic Redundancy Check (CRC) errors indicate packets were corrupted in transit, usually due to bad cables, connectors, or EMI.',
    weight: 10,
  },
  {
    id: 'deep9',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A user reports extremely slow network performance. The technician notices that the switch port is set to Full-Duplex while the workstation is set to Half-Duplex. What is this issue called?',
    options: ['Duplex Mismatch', 'Speed Incompatibility', 'Auto-negotiation loop', 'Switching Loop'],
    correctAnswer: 'Duplex Mismatch',
    explanation: 'A duplex mismatch occurs when two connected devices use different duplex settings, causing collisions and significant performance degradation.',
    weight: 10,
  },
  {
    id: 'deep10',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A network monitor shows an interface is receiving "giants." What does this typically mean?',
    options: ['Packets exceed the MTU size', 'Packets are too small', 'Packets have invalid headers', 'The buffer is overflowing'],
    correctAnswer: 'Packets exceed the MTU size',
    explanation: 'Giants are packets that exceed the maximum transmission unit (MTU) size (usually 1518 bytes for standard Ethernet).',
    weight: 10,
  },
  {
    id: 'deep11',
    type: 'architect',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'An interface is reporting "runts." Which of the following is the BEST definition of a runt?',
    options: ['Packets smaller than 64 bytes', 'Packets larger than 1518 bytes', 'Packets with incorrect checksums', 'Packets that timed out'],
    correctAnswer: 'Packets smaller than 64 bytes',
    explanation: 'Runts are packets that are smaller than the minimum Ethernet frame size of 64 bytes, often caused by collisions.',
    weight: 10,
  },
  {
    id: 'deep12',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.4 Protocols',
    question: 'A technician is configuring a VoIP system. Which protocol is primarily responsible for establishing, maintaining, and terminating the call session?',
    options: ['SIP', 'RTP', 'RTCP', 'H.323'],
    correctAnswer: 'SIP',
    explanation: 'Session Initiation Protocol (SIP) handles the signaling for VoIP calls, while RTP carries the actual voice data.',
    weight: 10,
  },
  {
    id: 'deep13',
    type: 'multi-select',
    domain: '3.0 Operations',
    objective: '3.4 DNS Servers',
    question: 'Which of the following DNS server types is responsible for providing the final, definitive IP address mapping for a requested domain? (Select TWO).',
    options: ['Authoritative Name Server', 'Primary DNS Server', 'Recursive Resolver', 'Caching Server', 'Forwarder'],
    correctAnswer: ['Authoritative Name Server', 'Primary DNS Server'],
    explanation: 'Authoritative servers (which can be primary or secondary) hold the actual DNS records for a domain.',
    weight: 10,
  },
  {
    id: 'deep14',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'A security auditor recommends moving the IDS to a "passive" or "out-of-band" configuration. How will the IDS receive traffic in this setup?',
    options: ['Port Mirroring/TAP', 'Inline bridging', 'Proxy Server', 'SSL Decryption'],
    correctAnswer: 'Port Mirroring/TAP',
    explanation: 'Passive IDS receives a copy of traffic via a SPAN port (Port Mirroring) or a network TAP, ensuring it does not impact network latency.',
    weight: 10,
  },
  {
    id: 'deep15',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.2 Storage',
    question: 'Which storage protocol is designed specifically to run over high-speed Fibre Channel networks, providing low-latency, lossless block-level access?',
    options: ['FCP (Fibre Channel Protocol)', 'iSCSI', 'FCoE', 'SMB'],
    correctAnswer: 'FCP (Fibre Channel Protocol)',
    explanation: 'FCP is the standard protocol for transporting SCSI commands over Fibre Channel networks.',
    weight: 10,
  },
  // --- SUBNET TIME-ATTACK QUESTIONS ---
  {
    id: 'sub1',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'You are provided with the network 192.168.10.0/24. You need to create 4 equal-sized subnets. What will be the new subnet mask for these networks?',
    options: ['/25', '/26', '/27', '/28'],
    correctAnswer: '/26',
    explanation: 'To create 4 subnets (2^2), you need to borrow 2 bits from the host portion. /24 + 2 = /26.',
    weight: 10,
  },
  {
    id: 'sub2',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'Given the IP address 172.16.50.0/27, what is the maximum number of usable host addresses available in this subnet?',
    options: ['30', '32', '62', '14'],
    correctAnswer: '30',
    explanation: 'A /27 has 5 host bits remaining (32-27=5). 2^5 = 32 total addresses. Subtract 2 for network and broadcast: 32 - 2 = 30 usable hosts.',
    weight: 10,
  },
  {
    id: 'sub3',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'What is the CIDR equivalent for the subnet mask 255.255.255.224?',
    options: ['/27', '/28', '/26', '/25'],
    correctAnswer: '/27',
    explanation: '224 in binary is 11100000. This adds 3 bits to the default /24, making it 27 bits total.',
    weight: 10,
  },
  {
    id: 'sub4',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'An organization needs a subnet for 500 users. Which of the following is the MOST efficient subnet mask for this requirement?',
    options: ['/23', '/22', '/24', '/21'],
    correctAnswer: '/23',
    explanation: 'A /23 provides 2^9 = 512 total addresses (510 usable), which is the smallest mask that accommodates 500 users.',
    weight: 10,
  },
  {
    id: 'sub5',
    type: 'subnet',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'Which of the following is the correct wildcard mask for a /28 subnet?',
    options: ['0.0.0.15', '0.0.0.31', '0.0.0.7', '0.0.0.63'],
    correctAnswer: '0.0.0.15',
    explanation: 'A /28 mask is 255.255.255.240. The wildcard mask is the inverse: 0.0.0.(255-240) = 0.0.0.15.',
    weight: 10,
  },
  // --- MODERN SYLLABUS UPGRADES (IaC, ZTA, IPv6, HA) ---
  {
    id: 'iac1',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.1 IaC',
    question: 'A DevOps engineer notices that several servers have slightly different configurations despite being deployed from the same initial script. This deviation from the intended state is known as:',
    options: ['Configuration Drift', 'Dynamic Inventory', 'Mutable Infrastructure', 'Orchestration Lag'],
    correctAnswer: 'Configuration Drift',
    explanation: 'Configuration drift occurs when undocumented changes are made to systems over time, causing them to deviate from their baseline configuration.',
    weight: 10,
  },
  {
    id: 'ipv6_1',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'An organization is migrating to IPv6 but needs to allow its IPv6-only servers to communicate with legacy IPv4-only services on the internet. Which transition mechanism is BEST suited for this?',
    options: ['NAT64', 'Dual Stack', '6to4 Tunneling', 'ISATAP'],
    correctAnswer: 'NAT64',
    explanation: 'NAT64 allows IPv6-only clients to communicate with IPv4-only servers by translating the headers at a gateway.',
    weight: 10,
  },
  {
    id: 'zta_1',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.1 Security Concepts',
    question: 'In a Zero Trust Architecture, which principle ensures that users and applications are granted only the minimum level of access necessary to perform their functions?',
    options: ['Least Privilege', 'Implicit Trust', 'Defense in Depth', 'Micro-segmentation'],
    correctAnswer: 'Least Privilege',
    explanation: 'Least Privilege is the cornerstone of ZTA, ensuring that subjects only have access to resources required for their specific role.',
    weight: 10,
  },
  {
    id: 'ha1',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.2 High Availability',
    question: 'A network design requires two load balancers where both units simultaneously handle incoming traffic to maximize throughput. Which HA configuration is being used?',
    options: ['Active-Active', 'Active-Passive', 'N+1 Redundancy', 'Hot Standby'],
    correctAnswer: 'Active-Active',
    explanation: 'In an Active-Active configuration, all nodes simultaneously handle and share the traffic load. The key distinction is that Active-Active provides both load balancing and redundancy, whereas Active-Passive relies on a standby unit.',
    weight: 10,
  },
  {
    id: 'ha2',
    type: 'architect',
    domain: '3.0 Operations',
    objective: '3.2 High Availability',
    question: 'A critical firewall cluster is configured so that one unit processes all traffic while the second unit monitors the first and only takes over if the primary unit fails. What is this configuration called?',
    options: ['Active-Passive', 'Active-Active', 'Load Balancing', 'Round Robin'],
    correctAnswer: 'Active-Passive',
    explanation: 'In an Active-Passive (Failover) configuration, one unit is active while the other remains in a standby/idle state. The standby unit only processes traffic if the active unit fails. It does NOT share the load.',
    weight: 10,
  },
  {
    id: 'cli_i1',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A technician suspect a DNS issue. Type the full command to interactively query the default DNS server for information about "google.com".',
    options: [], // Not used for interactive
    correctAnswer: 'nslookup google.com',
    explanation: 'The nslookup command is used to query DNS servers. Typing the domain name as an argument returns its A/AAAA records.',
    weight: 10,
  },
  {
    id: 'cli_i2',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'You need to identify all active TCP connections and the specific process ID (PID) associated with each. Type the Windows command to display this.',
    options: [],
    correctAnswer: 'netstat -ano',
    explanation: 'In Windows, "netstat -ano" displays all active connections, numerical addresses, and the owning process ID.',
    weight: 10,
  },
  {
    id: 'cli_i3',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'A user is reporting slow connectivity to a server in a different city. Type the command to trace the path to "10.0.50.1" and show the latency at each hop (Windows syntax).',
    options: [],
    correctAnswer: 'tracert 10.0.50.1',
    explanation: 'The tracert command in Windows sends ICMP Echo Requests with increasing TTL values to identify every router in the path.',
    weight: 10,
  },
  {
    id: 'cli_i4',
    type: 'cli-interactive',
    domain: '5.0 Troubleshooting',
    objective: '5.5 Software Tools',
    question: 'Type the command to see the local machine\'s ARP cache to verify MAC-to-IP mappings.',
    options: [],
    correctAnswer: 'arp -a',
    explanation: 'The "arp -a" command displays the Address Resolution Protocol (ARP) table.',
    weight: 10,
  },
  {
    id: 'zta_2',
    type: 'architect',
    domain: '4.0 Security',
    objective: '4.1 Security Concepts',
    question: 'Which ZTA component is responsible for making the final decision to grant or deny access to a resource based on real-time policy evaluation?',
    options: ['Policy Decision Point (PDP)', 'Policy Enforcement Point (PEP)', 'Identity Provider (IdP)', 'SIEM'],
    correctAnswer: 'Policy Decision Point (PDP)',
    explanation: 'The PDP evaluates the access request against defined policies and context to determine if access should be permitted.',
    weight: 10,
  },
  {
    id: 'ipv6_2',
    type: 'architect',
    domain: '1.0 Concepts',
    objective: '1.3 IP Addressing',
    question: 'A network administrator is configuring a router to encapsulate IPv6 packets inside IPv4 headers to allow them to cross an IPv4-only core network. This is known as:',
    options: ['Tunneling', 'Dual Stack', 'NAT-PT', 'Static Mapping'],
    correctAnswer: 'Tunneling',
    explanation: 'Tunneling encapsulates one protocol into another to cross incompatible network segments.',
    weight: 10,
  },
  // --- SYSLOG PBQS ---
  {
    id: 'log1',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Common Issues',
    question: 'A network administrator is investigating a report that a critical server is intermittently losing connection to the network. Analyze the switch logs below and identify the line that explains why the server is disconnected.',
    options: [],
    logData: [
      'May 19 04:12:01.234: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up',
      'May 19 04:12:05.102: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to up',
      'May 19 04:15:33.882: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to down',
      'May 19 04:15:38.221: %PM-4-ERR_DISABLE: psecure-violation error detected on Gi0/1, putting Gi0/1 in err-disable state',
      'May 19 04:15:38.225: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to down'
    ],
    correctLogIndex: 3,
    correctAnswer: '3',
    explanation: 'The log reflects an "err-disable" status caused by a port security violation. This happens when the switch detects more MAC addresses than allowed on a single port.',
    weight: 10,
  },
  {
    id: 'log2',
    type: 'syslog',
    domain: '4.0 Security',
    objective: '4.3 Security Features',
    question: 'An external consultant is auditing the corporate firewall. Users are complaining they cannot access the new web portal on 10.50.2.100. Identify the ACL entry causing the traffic drop.',
    options: [],
    logData: [
      'access-list 101 permit tcp 192.168.1.0 0.0.0.255 any eq 80',
      'access-list 101 permit tcp 192.168.1.0 0.0.0.255 any eq 443',
      'access-list 101 deny tcp any host 10.50.2.100 eq 443',
      'access-list 101 permit udp any any eq 53',
      'access-list 101 permit icmp any any'
    ],
    correctLogIndex: 2,
    correctAnswer: '2',
    explanation: 'The explicit "deny tcp any host 10.50.2.100 eq 443" entry blocks all HTTPS traffic destined for that specific server.',
    weight: 10,
  },
  {
    id: 'log3',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.3 Routing Issues',
    question: 'A router is failing to reach a remote network (172.16.20.0/24). Examine the routing table and identify the entry that conflicts with the intended destination.',
    options: [],
    logData: [
      'C    192.168.1.0/24 is directly connected, GigabitEthernet0/0',
      'L    192.168.1.1/32 is directly connected, GigabitEthernet0/0',
      'S    172.16.20.0/24 [1/0] via 10.0.0.5',
      'S    172.16.20.0/24 [1/5] is directly connected, Null0',
      'C    10.0.0.0/30 is directly connected, Serial0/0/0'
    ],
    correctLogIndex: 3,
    correctAnswer: '3',
    explanation: 'The entry "172.16.20.0/24 [1/5] is directly connected, Null0" is a static route redirecting all traffic for that subnet to the Null0 interface (the bit bucket), effectively dropping it.',
    weight: 10,
  },
  {
    id: 'log4',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Wireless Issues',
    question: 'A user is unable to connect to the "Internal-Secure" SSID. Review the RADIUS server logs and identify why the authentication is failing.',
    options: [],
    logData: [
      '2026-05-19 14:02:01: Sending Access-Request to 10.1.1.5:1812',
      '2026-05-19 14:02:01: User "jdoe" authenticated via EAP-TLS',
      '2026-05-19 14:10:45: Sending Access-Request to 10.1.1.5:1812',
      '2026-05-19 14:10:46: Received Access-Reject for User "admin_test": Shared secret mismatch',
      '2026-05-19 14:12:30: Sending Access-Request to 10.1.1.5:1812',
      '2026-05-19 14:12:31: User "guest" authenticated via PEAP-MSCHAPv2'
    ],
    correctLogIndex: 3,
    correctAnswer: '3',
    explanation: 'The log clearly states "Shared secret mismatch", which indicates the password/secret configured on the Wireless LAN Controller (WLC) does not match the secret on the RADIUS server.',
    weight: 10,
  },
  {
    id: 'log5',
    type: 'syslog',
    domain: '5.0 Troubleshooting',
    objective: '5.2 Physical Issues',
    question: 'A network technician is monitoring a core switch. SFP module performance is dropping. Identify the line indicating a hardware-level optical failure.',
    options: [],
    logData: [
      'GigabitEthernet1/0/1 is up, line protocol is up (connected)',
      'Full-duplex, 1000Mb/s, link type is auto, media type is 1000BaseSX',
      'Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0',
      'Received 124312384 bytes, 214151 unicasts, 0 runts, 0 giants, 0 throttles',
      '0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored',
      'Optical Receive Power: -40.2 dBm (Low Alarm Threshold: -30.0 dBm)',
      'Last clearing of "show interface" counters never'
    ],
    correctLogIndex: 5,
    correctAnswer: '5',
    explanation: 'The optical receive power of -40.2 dBm is well below the low alarm threshold of -30.0 dBm, indicating a "low light" condition, likely due to a dirty connector or failing fiber.',
    weight: 10,
  }
];
